// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDREhJb9U68KmE_yNnMB4yIPVKSHqC43FY',
    appId: '1:824900840335:web:65edd1b2c4ee53d51379fa',
    messagingSenderId: '824900840335',
    projectId: 'maarif-567b8',
    authDomain: 'maarif-567b8.firebaseapp.com',
    storageBucket: 'maarif-567b8.appspot.com',
    measurementId: 'G-7SHFWHMX6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3zh-vskGQObMeWiCSk1XF6hjV9HNeYNQ',
    appId: '1:824900840335:android:9ebdc5a4d860e3c51379fa',
    messagingSenderId: '824900840335',
    projectId: 'maarif-567b8',
    storageBucket: 'maarif-567b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhzkm_psvlZ1D0qFQm8_7_cW8UadhXyBg',
    appId: '1:824900840335:ios:71ea0d97d68de71a1379fa',
    messagingSenderId: '824900840335',
    projectId: 'maarif-567b8',
    storageBucket: 'maarif-567b8.appspot.com',
    iosClientId: '824900840335-18ccmpgvqbjae4dfa12451naf9qqmd3o.apps.googleusercontent.com',
    iosBundleId: 'com.maarif.maarifkids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhzkm_psvlZ1D0qFQm8_7_cW8UadhXyBg',
    appId: '1:824900840335:ios:ed0e7286e7d831091379fa',
    messagingSenderId: '824900840335',
    projectId: 'maarif-567b8',
    storageBucket: 'maarif-567b8.appspot.com',
    iosClientId: '824900840335-2ktihpdsf2jn4j1kipp3q68mj69f0bdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.maarifkids.RunnerTests',
  );
}
